// Generated by gencpp from file camera/messageRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_MESSAGEREQUEST_H
#define CAMERA_MESSAGE_MESSAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct messageRequest_
{
  typedef messageRequest_<ContainerAllocator> Type;

  messageRequest_()
    : if_request(0)  {
    }
  messageRequest_(const ContainerAllocator& _alloc)
    : if_request(0)  {
  (void)_alloc;
    }



   typedef int32_t _if_request_type;
  _if_request_type if_request;





  typedef boost::shared_ptr< ::camera::messageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::messageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct messageRequest_

typedef ::camera::messageRequest_<std::allocator<void> > messageRequest;

typedef boost::shared_ptr< ::camera::messageRequest > messageRequestPtr;
typedef boost::shared_ptr< ::camera::messageRequest const> messageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::messageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::messageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::messageRequest_<ContainerAllocator1> & lhs, const ::camera::messageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.if_request == rhs.if_request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::messageRequest_<ContainerAllocator1> & lhs, const ::camera::messageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::messageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::messageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf853f9571ad9688abfb5c1e3565de2c";
  }

  static const char* value(const ::camera::messageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf853f9571ad9688ULL;
  static const uint64_t static_value2 = 0xabfb5c1e3565de2cULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/messageRequest";
  }

  static const char* value(const ::camera::messageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 客户端请求时发送的两个数字\n"
"int32 if_request\n"
;
  }

  static const char* value(const ::camera::messageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::messageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.if_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct messageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::messageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::messageRequest_<ContainerAllocator>& v)
  {
    s << indent << "if_request: ";
    Printer<int32_t>::stream(s, indent + "  ", v.if_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_MESSAGEREQUEST_H
